# Generated by Django 5.1.7 on 2025-09-06 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pool', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='is_calculated',
            field=models.BooleanField(default=False),
        ),
    ]
