# Generated by Django 5.1.7 on 2025-09-06 10:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pool', '0002_shop_is_calculated'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='pool_customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='pool.pool'),
            preserve_default=False,
        ),
    ]
