# Generated by Django 5.1.7 on 2025-09-06 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pool', '0003_shop_pool_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='pool',
            name='cabinet_number',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
