# Generated by Django 5.1.7 on 2025-09-08 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pool', '0005_pool_created_at_pool_updated_at_shop_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pool',
            name='rent',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='pool',
            name='tools',
            field=models.JSONField(default=list),
        ),
    ]
